# Generated by Django 4.0.5 on 2023-02-23 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('famers', '0002_remove_farmer_full_name_farmer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
