# Generated by Django 4.0.5 on 2023-02-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('famers', '0005_farmer_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='uuid',
        ),
    ]
