# Generated by Django 4.0.5 on 2023-02-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famers', '0008_farmer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
