# Generated by Django 4.0.5 on 2023-02-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famers', '0009_farmer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
