# Generated by Django 4.1.7 on 2023-02-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("famers", "0011_subsidized"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subsidized",
            old_name="market_price",
            new_name="price",
        ),
    ]
