# Generated by Django 4.1.7 on 2023-02-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("famers", "0012_rename_market_price_subsidized_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subsidized",
            old_name="subsidized_price",
            new_name="market_price",
        ),
    ]
